<?php
//错误号都1w起，避免和系统级别的错误混淆
define('ERROR_NONE', 0);
define('ERROR_MOBILE_NUMBER_EXISTS', 10001);
define('ERROR_MOBILE_NUMBER_INVALID', 10002);
define('ERROR_CAPTCHA_INVALID', 10003);
define('ERROR_MOBILE_CAPTCHA_INVALID', 10004);
define('ERROR_INVALID_PARAM', 10005);
define('ERROR_PASSWORD_LENGTH_INVALID', 10006);
define('ERROR_MOBILE_NUMBER_NOT_EXISTS', 10007);
define('ERROR_LOGIN_PASSWORD_ERROR', 10008);
define('ERROR_LOGIN_MOBILE_OR_PASSWORD_EMPTY', 10009);




define('ERROR_GET_MONGODB_CONNECTION_FAILED', 20000);
define('ERROR_SELECT_MONGODB_COLLECTION_FAILED', 20001);